---
title: "Nnena UI"
author: "Jake Huang"
date: "01/12/2021"
output: html_document
runtime: shiny
---

```{r context='setup',include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tibble)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(shiny)
#library(jsonlite)
library(RColorBrewer)
library(h2o)
library(glue)
```


```{r tx_input}
wellPanel(style = "background: #FFF;",
          h4('Please enter the following information.'),
          flowLayout(
            numericInput('tx_age','Age',min=45,max=85,step=1,value = 66),
            numericInput('tx_psa','PSA (ng/mL)',value=6,min=0,step=1),
            numericInput('tx_bmi', 'BMI', value=0, min=0, step=1),
            numericInput('tx_glandvol', 'Glandvol', min=0, max=200, step=1, value=50),
            selectInput('tx_bxgs_1','Primary Gleason score',
                        c('Less than or equal to 3'=3,
                          '4'=4,
                          '5'=5),
                        selected=3),
            selectInput('tx_bxgs_2','Secondary Gleason score',
                        c('Less than or equal to 3'=3,
                          '4'=4,
                          '5'=5),
                        selected=3),
            selectInput('tx_diab','Do you have diabetes?',
                        choices=c('Yes','No'),selected='No'),
            checkboxGroupInput("tx_gdycat", "Dynamic Category",
                               c("Baseline" = "baseline",
                                 "Month 3"  = "mo3",
                                 "Month 6"  = "mo6",
                                 "Month 12" = "mo12"
                                 ))
      ),
      conditionalPanel( #BASELINE
        condition = "input.tx_gdycat.includes(\"baseline\")",
        selectInput('tx_baseline_ss', 'Baseline Sexual Satisfaction',
                    c(NA,'1'=1,'2'=2,'3'=3,'4'=4,'5'=5), selected=NA),
        numericInput('tx_baseline_sds', 'Baseline Sexual Domain Score',
                     min=0, max=100, value=NA)
      ),
      conditionalPanel( # MONTH 3
        condition = "input.tx_gdycat.includes(\"mo3\")",
        selectInput('tx_mo3_ss', 'Month 3 Sexual Satisfaction',
                    c(NA,'1'=1,'2'=2,'3'=3,'4'=4,'5'=5), selected=NA),
        numericInput('tx_mo3_sds', 'Month 3 Sexual Domain Score',
                     min=0, max=100, value=NA)
      ),
      conditionalPanel( # MONTH 6
        condition = "input.tx_gdycat.includes(\"mo6\")",
        selectInput('tx_mo6_ss', 'Month 6 Sexual Satisfaction',
                    c(NA,'1'=1,'2'=2,'3'=3,'4'=4,'5'=5), selected=NA),
        numericInput('tx_mo6_sds', 'Month 6 Sexual Domain Score',
                     min=0, max=100, value=NA)
      ),
      conditionalPanel( # MONTH 12
        condition = "input.tx_gdycat.includes(\"mo12\")",
        selectInput('tx_mo12_ss', 'Month 12 Sexual Satisfaction',
                    c(NA,'1'=1,'2'=2,'3'=3,'4'=4,'5'=5), selected=NA),
        numericInput('tx_mo12_sds', 'Month 12 Sexual Domain Score',
                     min=0, max=100, value=NA)
      ),
      br(),
      actionButton('tx_start','Calculate')
)



```

```{r tx_output}

conditionalPanel('input.tx_start>0 && !input.tx_gdycat.includes(\"mo12\")',
                 wellPanel(id='tx_results',style = "background: #FFF;",
                   h3('Month 12 Epic Sexual Domain Score: '),
                   h5(htmlOutput('mo12_sds')),
                   h3('Month 12 Erection Quality Score: '),
                   h5(htmlOutput('mo12_eqs'))
                   ))

conditionalPanel('input.tx_start>0',
                 wellPanel(id='tx_results12',style = "background: #FFF;",
                   h3('Month 24 Epic Sexual Domain Score: '),
                   h5(htmlOutput('mo24_sds')),
                   h3('Month 24 Erection Quality Score: '),
                   h5(htmlOutput('mo24_eqs'))
                   ))
####
```


```{r tx_prediction}

ggfind = reactive({
  b1 = as.integer(input$tx_bxgs_1)
  b2 = as.integer(input$tx_bxgs_2)
  if ((b1 + b2) == 6) {
    gg = 'GG1'
  } else if (b1 == 3 & b2 == 4) {
    gg = 'GG2'
  } else if (b1 == 4 & b2 == 3) {
    gg = 'GG3'
  } else if ((b1 + b2) == 8) {
    gg = 'GG4'
  } else if ((b1 + b2) >= 9){
    gg = 'GG5'
  }
  gg
})

# this function gets all the dynamic categories the user
# selected and inserts a "|" in between (except for the last one)
getdycat <- reactive({
  dc = input$tx_gdycat
  dc_piped=""
  if (is.null(input$tx_gdycat)) { dc_piped="none_of_the_above" } 
  else { dc_piped = glue_collapse(dc, sep="|") }
  dc_piped
})

createDF <- reactive({
  
  age=as.integer(input$tx_age)
  bmi=as.integer(input$tx_bmi)
  diabetes = ifelse(input$tx_diab=='Yes', 1, 0)
  glandvol = as.integer(input$tx_glandvol)
  psa = as.integer(input$tx_psa)
  gleason_grade = ggfind()
  dynamic_category = getdycat()
  outcome_time = "mo12"
  baseline_sexual_satisfaction = as.integer(input$tx_baseline_ss)
  baseline_epic_sexualdomainscore = as.integer(input$tx_baseline_sds)
  mo3_sexual_satisfaction= as.integer(input$tx_mo3_ss)
  mo3_epic_sexualdomainscore = as.integer(input$tx_mo3_sds)
  mo6_sexual_satisfaction = as.integer(input$tx_mo6_ss)
  mo6_epic_sexualdomainscore = as.integer(input$tx_mo6_sds)
  mo12_sexual_satisfaction=as.integer(input$tx_mo12_ss)
  mo12_epic_sexualdomainscore=as.integer(input$tx_mo12_sds)

  df_usrinput = data.frame(age,
                           bmi,
                           diabetes,
                           glandvol,
                           psa,
                           gleason_grade,
                           dynamic_category,
                           outcome_time,
                           baseline_sexual_satisfaction,
                           baseline_epic_sexualdomainscore,
                           mo3_sexual_satisfaction,
                           mo3_epic_sexualdomainscore,
                           mo6_sexual_satisfaction,
                           mo6_epic_sexualdomainscore,
                           mo12_sexual_satisfaction,
                           mo12_epic_sexualdomainscore
                           )
  df_usrinput
})


### MONTH 12
output$mo12_sds <- renderText({ 
  x = createDF()
  x$outcome_time="mo12"
  pred_isof <- h2o.mojo_predict_df(frame=x, 
                                   mojo_zip_path='h2o_rf_epic_sexualdomainscore.zip',
                                   genmodel_jar_path='h2o-genmodel.jar',
                                   verbose = F)
  score = as.vector(pred_isof$predict)  
  paste(score)
})

output$mo12_eqs <- renderText({ 
  x = createDF()
  x$outcome_time="mo12"
  pred_isof <- h2o.mojo_predict_df(frame=x, 
                                   mojo_zip_path='h2o_rf_outcome_erection_quality_high.zip',
                                   genmodel_jar_path='h2o-genmodel.jar',
                                   verbose = F)
  score = as.vector(pred_isof$Yes)  
  paste(score)
})

### MONTH 24
output$mo24_sds <- renderText({ 
  x = createDF()
  x$outcome_time="mo24"
  pred_isof <- h2o.mojo_predict_df(frame=x, 
                                   mojo_zip_path='h2o_rf_epic_sexualdomainscore.zip',
                                   genmodel_jar_path='h2o-genmodel.jar',
                                   verbose = F)
  score = as.vector(pred_isof$predict)  
  paste(score)
})

output$mo24_eqs <- renderText({ 
  x = createDF()
  x$outcome_time="mo24"
  pred_isof <- h2o.mojo_predict_df(frame=x, 
                                   mojo_zip_path='h2o_rf_outcome_erection_quality_high.zip',
                                   genmodel_jar_path='h2o-genmodel.jar',
                                   verbose = F)
  score = as.vector(pred_isof$Yes)  
  paste(score)
})

```
      